On Python 3, procmon now handles process output without exceptions
